### ISSUE TITLE
Crash due to missing Android-internal field on API > 23

### ISSUE THREAD

**Issue by magneticflux-** [modular-ftc/robotcore-repackaged#6]
The source of the exception: `com.qualcomm.robotcore.util.ClassUtil$MappedByteBufferInfo` calls `getType()` on a null object (`blockField`) because it isn't found.

It appears to be a hacky way to get a memory-mapped file handle to some native code by passing an address. Newer versions of Android replace the Android-specific `java.nio.MemoryBlock` class with a `java.io.FileDescriptor`.

Two solutions:
1. Make `addressField` do a null check
2. Find a way to get the same information from a `FileDescriptor` and switch on the API level to pick the appropriate field name.

**Comment by magneticflux-** [comment]
The full stack trace:
```
E/NetDiscover_wifiDirectAgent: field not found: java.lang.Object.block
E/NetDiscover_wifiDirectAgent: java.lang.NoSuchFieldException: No field block in class Ljava/lang/Object; (declaration of 'java.lang.Object' appears in /system/framework/core-oj.jar)
E/NetDiscover_wifiDirectAgent:     at java.lang.Class.getDeclaredField(Native Method)
E/NetDiscover_wifiDirectAgent:     at com.qualcomm.robotcore.util.ClassUtil.getDeclaredField(ClassUtil.java:158)
E/NetDiscover_wifiDirectAgent:     at com.qualcomm.robotcore.util.ClassUtil.getDeclaredField(ClassUtil.java:168)
I/chatty: uid=10137(com.qualcomm.ftcrobotcontroller) identical 1 line
E/NetDiscover_wifiDirectAgent:     at com.qualcomm.robotcore.util.ClassUtil.getDeclaredField(ClassUtil.java:168)
        at com.qualcomm.robotcore.util.ClassUtil$MappedByteBufferInfo.<clinit>(ClassUtil.java:294)
E/NetDiscover_wifiDirectAgent:     at java.lang.Class.classForName(Native Method)
E/NetDiscover_wifiDirectAgent:     at java.lang.Class.forName(Class.java:453)
        at java.lang.Class.forName(Class.java:378)
E/NetDiscover_wifiDirectAgent:     at org.firstinspires.ftc.robotcore.internal.opmode.ClassManager.classNamesToClasses(ClassManager.java:186)
E/NetDiscover_wifiDirectAgent:     at org.firstinspires.ftc.robotcore.internal.opmode.ClassManager.processAllClasses(ClassManager.java:240)
        at com.qualcomm.ftccommon.ClassManagerFactory.processAllClasses(ClassManagerFactory.java:90)
E/NetDiscover_wifiDirectAgent:     at org.firstinspires.ftc.robotcontroller.internal.FtcRobotControllerActivity.onCreate(FtcRobotControllerActivity.java:284)
        at android.app.Activity.performCreate(Activity.java:7009)
E/NetDiscover_wifiDirectAgent:     at android.app.Activity.performCreate(Activity.java:7000)
E/NetDiscover_wifiDirectAgent:     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1214)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2731)
E/NetDiscover_wifiDirectAgent:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
E/NetDiscover_wifiDirectAgent:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
        at android.os.Handler.dispatchMessage(Handler.java:106)
E/NetDiscover_wifiDirectAgent:     at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
E/NetDiscover_wifiDirectAgent:     at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
E/NetDiscover_wifiDirectAgent:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
D/AndroidRuntime: Shutting down VM
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.qualcomm.ftcrobotcontroller, PID: 31756
    java.lang.ExceptionInInitializerError
        at java.lang.Class.classForName(Native Method)
        at java.lang.Class.forName(Class.java:453)
        at java.lang.Class.forName(Class.java:378)
        at org.firstinspires.ftc.robotcore.internal.opmode.ClassManager.classNamesToClasses(ClassManager.java:186)
        at org.firstinspires.ftc.robotcore.internal.opmode.ClassManager.processAllClasses(ClassManager.java:240)
        at com.qualcomm.ftccommon.ClassManagerFactory.processAllClasses(ClassManagerFactory.java:90)
        at org.firstinspires.ftc.robotcontroller.internal.FtcRobotControllerActivity.onCreate(FtcRobotControllerActivity.java:284)
        at android.app.Activity.performCreate(Activity.java:7009)
        at android.app.Activity.performCreate(Activity.java:7000)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1214)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2731)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Class java.lang.reflect.Field.getType()' on a null object reference
        at com.qualcomm.robotcore.util.ClassUtil$MappedByteBufferInfo.<clinit>(ClassUtil.java:295)
        at java.lang.Class.classForName(Native Method) 
        at java.lang.Class.forName(Class.java:453) 
        at java.lang.Class.forName(Class.java:378) 
        at org.firstinspires.ftc.robotcore.internal.opmode.ClassManager.classNamesToClasses(ClassManager.java:186) 
        at org.firstinspires.ftc.robotcore.internal.opmode.ClassManager.processAllClasses(ClassManager.java:240) 
        at com.qualcomm.ftccommon.ClassManagerFactory.processAllClasses(ClassManagerFactory.java:90) 
        at org.firstinspires.ftc.robotcontroller.internal.FtcRobotControllerActivity.onCreate(FtcRobotControllerActivity.java:284) 
        at android.app.Activity.performCreate(Activity.java:7009) 
        at android.app.Activity.performCreate(Activity.java:7000) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1214) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2731) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856) 
        at android.app.ActivityThread.-wrap11(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6494) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
```
